@startuml
'https://plantuml.com/use-case-diagram

left to right direction
actor User as user

package Application {
  usecase "New User\nRegistration" as register
  usecase "Login" as login
  usecase "Read\nInstructions" as instructions
  usecase "Access Library" as library
  usecase "Read Book" as book
}

user --> register
user --> login
user --> instructions
user --> library
user --> book

@enduml