@startuml

usecase email
usecase password
agent user

user -- email
user -- password

hexagon accesses

user -- accesses

agent library

accesses -- library

hexagon contains

library -- contains

agent stories

contains -- stories

agent chapters

usecase email
usecase password

@enduml
