@startuml
'https://plantuml.com/sequence-diagram

actor User
database "Firebase" as Firebase
participant "Library" as Library
participant "Book Cover" as Cover
participant "Chapters" as Chapter
participant "Bookmark" as Bookmark
participant "Story Map" as Map


User -> Library: Start Application
activate Library
User -> Firebase: Login
activate Firebase
Library -> Cover: Choose eBook
deactivate Library
activate Cover
Cover -> Chapter: Text & Image appears
deactivate Cover
activate Chapter
Firebase -> Chapter
Chapter --> Firebase: Toggle `Chapter Visited` boolean to `true`
Chapter -> Bookmark
Bookmark --> Firebase: Access database for Bookmark
Firebase --> Bookmark: Returns Bookmarked page
Bookmark -> Chapter: Bookmark becomes Chapter
Chapter -> Map
activate Map
Map -> Chapter
deactivate Map
Chapter -> Cover

@enduml
